### ISSUE TITLE
Options Transition when windows touch the panel & Transition with the overview doesn't work

### ISSUE THREAD

**Issue by CristianH033** [ewlsh/dynamic-panel-transparency#118]
The "Transition when windows touch the panel" and "Transition with the overview" options do not work, and by default the panel is only darkened when the window is maximized or when the overview is activated, the transition speed options do work.

I'm installing version 33 from the source with: `git clone https://github.com/rockon999/dynamic-panel-transparency.git`

I'm using ubuntu 20.04.

**Comment by ewlsh** [comment]
Fixed in #126.

**Comment by nahuelwexd** [comment]
In order not to open a new issue, I report it here, as it's related.

In version 35, "Transition with the overview" seems to still not work, when opening the overview the panel remains transparent. I've installed the extension both from e.g.o and from the master branch in git
